Sergey Molchun homework lesson 12
eugene-okulik/python_masters pull request #105
Opened 2023-12-17 18:41 UTC by Moserios

Homework for lesson 12

2024-01-06 07:34 UTC, eugene-okulik requested changes

2024-01-06 07:34 UTC, eugene-okulik commented on homework/sergey_molchun/lesson_12/main.py
> +print(finished_dict)
Это задание было на list comprehension, но ты его здесь не использовал.

2024-01-06 07:34 UTC, eugene-okulik commented on homework/sergey_molchun/lesson_12/main.py
> +converted = list(map(lambda x: x.split(" "), PRICE_LIST.splitlines()))
Ты сделал переменную lines_list, в которой хранишь PRICE_LIST.splitlines(), но почему-то ею не пользуешься.

2024-01-06 07:34 UTC, eugene-okulik commented on homework/sergey_molchun/lesson_12/main.py
> +print(finished_dict)
Вот этот for как раз можно переделать в list comprehension, ну, точнее, в dict comprehension

2024-01-09 22:33 UTC, Moserios commented
Updated

2024-01-13 07:15 UTC, eugene-okulik approved these changes

2024-01-13 07:15 UTC, merged