Sergey Molchun homework lesson 13
eugene-okulik/python_masters pull request #106
Opened 2023-12-17 20:13 UTC by Moserios

Sergey Molchun homework lesson 13

2024-01-06 07:40 UTC, eugene-okulik requested changes
В целом, классы оформил хорошо, но не точно выполнил требования к программе.

2024-01-06 07:40 UTC, eugene-okulik commented on homework/sergey_molchun/lesson_13/main.py
> +                 is_reserved=False):
Я спецом притянул за уши материал и наличие текста, чтобы у всех книг были характеристики, которые можно сделать общими. Вряд ли будет существовать книга без текста ))) Но сейчас у тебя это индивидуальная характеристика, которую можно задать при создании.

2024-01-06 07:40 UTC, eugene-okulik commented on homework/sergey_molchun/lesson_13/main.py
> +        # self.subject = subject
А чего subject решил не указывать?

2024-01-09 22:17 UTC, Moserios commented on homework/sergey_molchun/lesson_13/main.py
> +                 is_reserved=False):
Я немного знаком с издательством и могу сказать что материал у книг отличается от издания к изданию (плотность и размер страниц) и книги без текста тоже существуют, они известны под названиями журналы, ежедневники, записные книжки. Я могу добавить дефолтное свойство "page_binding" (переплет), создающееся в момент инициализации, он есть у всех книг.

2024-01-09 22:22 UTC, Moserios commented on homework/sergey_molchun/lesson_13/main.py
> +        # self.subject = subject
Так title используется для указания предмета. Всегда конкретно пишется что это за учебник.

2024-01-09 22:32 UTC, Moserios commented
Updated

2024-01-09 22:32 UTC, Moserios commented
Updated

2024-01-13 07:17 UTC, eugene-okulik commented on homework/sergey_molchun/lesson_13/main.py
> +        # self.subject = subject
Ну, может существовать книга с названием "Весь мир" по предмету география. Или книга "Складывай и умножай" по предмету математика.

2024-01-13 07:31 UTC, eugene-okulik approved these changes
В плане создания классов, всё хорошо.  
Но стоит понимать, что в команде все есть люди, которые отвечают за разные аспекты, и за требования кто-то отвечает и требования эти, скорее всего, согласованы. Умышленно идти против требований - не лучшая практика. В крайнем случае, это тоже должно быть согласовано.  
Особенно внимательным нужно быть в ходе собеседования и выполнения тестового. Если бы такое задание было тестовым, дальше бы ты не прошел.

2024-01-13 07:31 UTC, eugene-okulik commented on homework/sergey_molchun/lesson_13/main.py
> +                 is_reserved=False):
Но параметров плотность и размер страниц у нас здесь и нет. То есть, это все равно бумага. Но даже нет смысла лезть в эти тонкости, ведь есть требования

> Какие-то из атрибутов будут общими для всех книг (материал, наличие текста)

И является не очень хорошей практикой делать на свое усмотрение, то, что противоречит требованиям.  
В крайнем случае, если у тебя прямо рука не поднимается так сделать, нужно согласовать изменение требований.

2024-01-13 07:31 UTC, merged