Sergey Molchun homework lesson 16
eugene-okulik/python_masters pull request #123
Opened 2024-01-15 20:25 UTC by Moserios

Homework for lesson 16

2024-01-21 07:56 UTC, eugene-okulik requested changes

2024-01-21 07:56 UTC, eugene-okulik commented on homework/sergey_molchun/lesson_16/main.py
> +TARGET_PATH = fr"{CURRENT_PATH}\eugene_okulik\Lesson_16\hw"
У меня не работает. На моем компе слеши в другую сторону

2024-01-29 10:26 UTC, eugene-okulik requested changes

2024-01-29 10:26 UTC, eugene-okulik commented on homework/sergey_molchun/lesson_16/main.py
> +                .replace(r"\sergey_molchun\lesson_16", ""))
И всё еще не работает, так как у меня слеши в другую сторону

2024-01-29 14:49 UTC, Moserios commented
Fixed

2024-01-30 07:25 UTC, eugene-okulik approved these changes

2024-01-30 07:26 UTC, merged