natallia_mazuryna: homework 6 completed
eugene-okulik/python_masters pull request #124
Opened 2024-01-15 22:54 UTC by nmazuryna

2024-01-21 07:58 UTC, eugene-okulik requested changes

2024-01-21 07:58 UTC, eugene-okulik commented on homework/natallia_mazuryna/homework_6/Task_2.py
> +first_result_number_index = first_result_line.index('42')
Если мы еще при создании программы знаем, что там число 42, то можно просто написать `print(42 + 10)`  
Идея программы в том, что она сама находит число в этой строке и делает с ним, что нужно. Для этого нужно найти что-то одинаковое во всех строках. Количество символов до числа разное, количество символов в самом числе тоже разное, но кое что в структуре строки есть одинаковое.

2024-01-21 14:54 UTC, nmazuryna commented on homework/natallia_mazuryna/homework_6/Task_2.py
> +first_result_number_index = first_result_line.index('42')
привет! спасибо, что глянул, если правильно поняла - то переделала немножко, чтобы смотрели не на конкретное число, а на любое число после :

2024-01-29 10:27 UTC, eugene-okulik approved these changes
Ага. Всё правильно поняла

2024-01-29 10:27 UTC, merged