Sergey Molchun lesson 30
eugene-okulik/python_masters pull request #156
Opened 2024-03-04 17:48 UTC by Moserios

Test #2 impossible to remove time.sleep(2).

2024-03-04 21:06 UTC, eugene-okulik requested changes

2024-03-04 21:06 UTC, eugene-okulik commented on homework/sergey_molchun/Lesson_30/test_main.py
> +    add_to_compare_button.click()
Честно говоря, вообще не представляю почему это работает. Кнопка добавления к сравнению доступна только когда мышка наведена на товар. То есть эти два действия должны находиться в одной непрерывной последовательности: навести.кликнуть.перформ  
И тогда никакой слип не нужен.

2024-03-04 21:06 UTC, eugene-okulik commented on homework/sergey_molchun/Lesson_30/test_main.py
> +    add_to_compare_button.click()
И даже ожидание этой кнопки не нужно.

2024-03-05 14:02 UTC, Moserios commented
Lesson 30 test 2 fixed

2024-03-05 20:21 UTC, eugene-okulik approved these changes

2024-03-05 20:21 UTC, merged