Elizaveta: homework 4 completed
eugene-okulik/python_masters pull request #36
Opened 2023-11-23 21:34 UTC by lzbglk123

Homework 4 done

2023-11-23 21:50 UTC, lzbglk123 commented
Почему он скушал первый коммит c файликом, а остальные нет?(

2023-11-24 21:39 UTC, eugene-okulik commented
> Почему он скушал первый коммит c файликом, а остальные нет?(

Ну, файлик был пустой. А потом в нем появилось содержимое. И вот оформление содержимого ему не нравится

2023-11-24 21:40 UTC, lzbglk123 commented
> > Почему он скушал первый коммит c файликом, а остальные нет?(
> 
> Ну, файлик был пустой. А потом в нем появилось содержимое. И вот оформление содержимого ему не нравится

Я про коммит, где уже файлик был. Посмотри плиз его, я там неправильно потом оформление сделала.

2023-11-24 21:43 UTC, eugene-okulik commented
> > > Почему он скушал первый коммит c файликом, а остальные нет?(
> > 
> > 
> > Ну, файлик был пустой. А потом в нем появилось содержимое. И вот оформление содержимого ему не нравится
> 
> Я про коммит, где уже файлик был. Посмотри плиз его, я там неправильно потом оформление сделала.

Ну, тот файлик, который прошел нормально проверку, был пустой.
Следующий коммит github почему-то заигнорил и вообще перестал проверять.
А в следующих уже начал находить проблемы.

2023-11-24 21:45 UTC, eugene-okulik requested changes

2023-11-24 21:45 UTC, eugene-okulik commented on homework/elizaveta_buglak/homework_4/program for homework_4.py
> +        print((int(cost_purchase/amount_save)), 'months left before purchase')
Сейчас тебе осталось вот здесь вокруг знака деления поставить пробелы

2023-11-24 21:45 UTC, eugene-okulik commented on homework/elizaveta_buglak/homework_4/program for homework_4.py
> +              (int(cost_purchase/amount_save)), 'months')
И вот здесь вокруг деления тоже.

2023-11-24 21:59 UTC, eugene-okulik approved these changes
На тебя нашло вдохновение прям написать целую программу с условиями, но почему-то заточенную чисто под феррари )))

2023-11-24 22:00 UTC, merged