homework_5_roman_gusarov_done
eugene-okulik/python_masters pull request #40
Opened 2023-11-25 07:21 UTC by rsgusarov

2023-11-30 10:17 UTC, eugene-okulik requested changes

2023-11-30 10:17 UTC, eugene-okulik commented on homework/roman_gusarov/homework_5/homework_5.py
> +my_dict2['i am a tuple'] = 600
Проверку на внимательность не прошел. Ты выполнил задание

> добавьте элемент с ключом 'i am a tuple' и любым значением

а нужно было

> добавьте элемент с ключом ('i am a tuple',) и любым значением

2023-11-30 10:17 UTC, eugene-okulik commented on homework/roman_gusarov/homework_5/homework_5.py
> +print(my_dict['tuple'][4])
Так ты получил пятый элемент кортежа. Для получения последнего есть специальный индекс

2023-12-01 09:50 UTC, rsgusarov commented on homework/roman_gusarov/homework_5/homework_5.py
> +print(my_dict['tuple'][4])
Привет, корректный запрос на последний элемент будет выглядеть так:
print(my_dict['tuple'][-1])

2023-12-01 10:03 UTC, rsgusarov commented on homework/roman_gusarov/homework_5/homework_5.py
> +my_dict2['i am a tuple'] = 600
> Проверку на внимательность не прошел. Ты выполнил задание
> 
> > добавьте элемент с ключом 'i am a tuple' и любым значением
> 
> а нужно было
> 
> > добавьте элемент с ключом ('i am a tuple',) и любым значением

Исправил оба замечания в документе.

2023-12-01 12:04 UTC, eugene-okulik approved these changes

2023-12-01 12:05 UTC, merged